# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a495b2358b0cecc23f50235c07d385e2d67ac303b88845e22e7c2fced09f0db24a8d1e50d14ef020b75d3b1a7eb4ebbdfb032a2d6d91b5790434e9a4719fd778

test:
  secret_key_base: 693ae02485bb286bd4fb694b570c0c1ec3e4f7ba978e2b8e26dcb2d635daa1b646a94765e4e2b260d9e1d5b741513a9635a6816b3519371a4f490f454dbe2666

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
